project_id = "rxlrwephzfsmzspyjsdd"

[functions.follow]
verify_jwt = true

[functions.unfollow]
verify_jwt = true

[functions.follow-requests]
verify_jwt = true

[functions.user-settings]
verify_jwt = true

[functions.search-people]
verify_jwt = true

[functions.game-reward]
verify_jwt = true

[functions.game-inventory]
verify_jwt = true

[functions.game-craft]
verify_jwt = true

[functions.game-recipes]
verify_jwt = false

[functions.game-gift]
verify_jwt = true