name: Automerge

on:
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: >-
      github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Find open PRs for this ref
        uses: actions/github-script@v7
        id: find
        with:
          script: |
            const { owner, repo } = context.repo;
            const prs = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${context.payload.check_suite.head_branch}`
            });
            core.setOutput('number', prs.data[0]?.number || '');
      - name: Merge PR
        if: steps.find.outputs.number != ''
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const number = Number(process.env.PR_NUMBER);
            await github.rest.pulls.merge({ owner, repo, pull_number: number, merge_method: 'squash' });
        env:
          PR_NUMBER: ${{ steps.find.outputs.number }}
