name: CI

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Detect package manager
      id: detect-pm
      run: |
        if [ -f "pnpm-lock.yaml" ]; then
          echo "pm=pnpm" >> $GITHUB_OUTPUT
        else
          echo "pm=npm" >> $GITHUB_OUTPUT
        fi
        
    - name: Install dependencies
      run: |
        if [ "${{ steps.detect-pm.outputs.pm }}" = "pnpm" ]; then
          npm install -g pnpm
          pnpm install --frozen-lockfile
        else
          npm ci
        fi
        
    - name: Run type check
      run: |
        if [ "${{ steps.detect-pm.outputs.pm }}" = "pnpm" ]; then
          pnpm typecheck
        else
          npm run typecheck
        fi
        
    - name: Run linter
      run: |
        if [ "${{ steps.detect-pm.outputs.pm }}" = "pnpm" ]; then
          pnpm lint
        else
          npm run lint
        fi
        
    - name: Build project
      run: |
        if [ "${{ steps.detect-pm.outputs.pm }}" = "pnpm" ]; then
          pnpm build
        else
          npm run build
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/
        retention-days: 1
